name: Postman-test.yml
on:
  push:
    branches:
      - main

jobs:
  postman-test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Install Node.js on the runner
      - name: Install Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

      # Install Newman and HTML Extra Reporter globally
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make a directory to upload the test results
      - name: Make Directory for Results
        run: mkdir -p testResults

      # Run the Postman collection and output to console
      - name: Run Postman Collection to Console
        run: |
          newman run ./postman-tests/user_management.postman_collection.json

      # Run the Postman collection and output to HTML report
      - name: Run Postman Collection to HTML Report
        run: |
          newman run ./postman-tests/user_management.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html

      # Upload the contents of the Test Results directory to workspace
      - name: Output the Run Details
        uses: actions/upload-artifact@v3  # Update to v3
        with: 
          name: RunReports
          path: testResults


