name: Postman-test.yml
on:
  push:
    branches:
      - main

jobs:
  postman-test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

      # Install newman and reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make Directory for Results
        run: mkdir -p testResults

      # Run the Postman collection to console
      - name: Run Postman Collection to Console
        run: |
          newman run automation-exercise.postman_collection.json

      # Run the Postman collection to HTML report
      - name: Run Postman Collection to HTML Report
        run: |
          newman run automation-exercise.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html

      # Upload the contents of the Test Results directory to workspace
      - name: Output the Run Details
        uses: actions/upload-artifact@v3
        with: 
          name: RunReports
          path: testResults

